server:
  port: 9002

web-resource-path: C:\Users\Eric Jin\Desktop\static\

spring:
  # 配置静态路径
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/static, classpath:/resources/, classpath:/public/, file:${web-resource-path}
  application:
    name: crazychat-user
  datasource:   # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.188.128:3306/crazychat_user?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:    # 配置jpa
    show-sql: true
    database: mysql
  # 发送邮件
  mail:
    username: 2789519045@qq.com
    password: zepghwtjqvijdcea    # 邮箱授权码
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true     # 开启ssl安全连接
  # redis配置
  redis:
    database: 0
    host: 192.168.188.128
    port: 6379
jwt:
  config:
    # 加盐
    key: ericjin
    ttl: 3600000

# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:4170/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问

# 验证用的key
auth-key: #$%^&~*()_+125fsdsdghuyurew&*^^%!@
# 访问域名
url-path: http://127.0.0.1:4140


