server:
  port: 9001

spring:
  application:
    name: crazychat-chat
  # mongodb配置
  data:
    mongodb:
      host: 152.136.68.61
      database: chatDB
  # redis配置
  redis:
    host: 152.136.68.61
    port: 6379
# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:4170/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问

    