server:
  port: 9001

spring:
  application:
    name: crazychat-chat
  # mongodb配置
  data:
    mongodb:
      host: 192.168.188.128
      database: chatDB
  # redis配置
  redis:
    host: 192.168.188.128
    port: 6379
# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:4170/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问

# 上传文件的路径
web-resource-path: C:\Users\Eric Jin\Desktop\static\
# 访问域名
url-path: http://127.0.0.1:4140


