server:
  port: 9004

spring:
  application:
    name: crazychat-relationchat
  data:
    mongodb:
      host: 152.136.68.61
      database: relationChatDB
  # redis配置
  redis:
    host: 152.136.68.61

# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:4170/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问

