server:
  port: 9004

spring:
  application:
    name: crazychat-relationchat
  data:
    mongodb:
      host: 172.17.98.177
      database: relationChatDB
  # redis配置
  redis:
    host: 172.17.98.177

# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:4170/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问

